config/routes.rb
Rails.application.routes.draw do
  get 'settings/change_locale'

  # gems generated routes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # custom routes
  root to: "home#index"
  get 'home/info'
  get 'home/help'
  post '/orders/load' , to: 'orders#load'
  post '/receipts/tax_evaluation' , to: 'receipts#tax_evaluation'

  # resources routes
  # for receipts
  resources :receipts
  # resources :mark_receipts, as: "receipts", :controller => "receipts", :type => "MarkReceipt", :branch => "M",
  # resources :identical_search_receipts, :controller => "receipts", :type => "IdenticalSearchReceipt", :branch => "M", :path => 'receipts'
  # resources :similar_search_receipts, :controller => "receipts", :type => "SimilarSearchReceipt", :branch => "M", :path => 'receipts'
  # resources :rectification_mark_receipts, :controller => "receipts", :type => "RectificationMarkReceipt", :branch => "M", :path => 'receipts'
  # for orders
  resources :orders, :controller => "orders", only: [:new, :create, :show, :index]
  resources :md_orders, :controller => "orders", only: [:new, :show, :index]
  resources :pd_orders, :controller => "orders", only: [:new, :show, :index]
  resources :md_orders, :controller => "orders", only: [:create,], :formats=>[:json]
  resources :pd_orders, :controller => "orders", only: [:create], :formats=>[:json]

  # Cahnge locale routes
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/views/partials/_accounting.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= I18n.t('menu.accounting') %><span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to(I18n.t('menu.order.other'), '/orders') %></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">prochainement...</a></li>
  </ul>
</li>

app/views/partials/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= flash_class_name(message_type) %> alert-dismissable">
    <span><%= message %></span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">INAPI</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <%= render 'partials/receipts' %>
      <%= render 'partials/accounting' %>
    </ul>
    <%= render 'partials/navstatus' %>
  </div>
</nav>

app/views/partials/_navlang.html.erb
<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
    <%= t('menu.languages.lang') %>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <%= link_to I18n.t('menu.languages.fr'), change_locale_path(:fr) %>
    </li>
    <li>
      <%= link_to I18n.t('menu.languages.en'), change_locale_path(:en) %>
    </li>
  </ul>
</li>

app/views/partials/_navstatus.html.erb
<ul class="nav navbar-nav navbar-right margin-navbar-right">
  <%= render 'partials/navlang' %>
  <% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= I18n.t('activerecord.models.user.one') %>:<%= current_user.fullname %><span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="/admin/"><%= I18n.t('menu.admin') %></a></li>
      <li><%= link_to I18n.t('menu.edit_profile'), edit_user_registration_path %></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to I18n.t("menu.logout"), destroy_user_session_path, :method=>'delete'%></li>
    </ul>
  </li>
  <% else %>
  <li><%= link_to I18n.t("menu.register"), new_user_registration_path %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= I18n.t("menu.login") %><span class="caret"></span></a>
      <ul class="dropdown-menu">
        <div class="new_session_user">
        <h4><%= I18n.t('menu.please_connect') %></h4>
        <hr />
          <%= render 'devise/sessions/user_form', place: "fragment" %> 
        </div>
      </ul>
  </li>
  <% end %>
</ul>

app/views/partials/_receipts.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= I18n.t('activerecord.models.receipt.new') %><span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to(I18n.t('menu.receipt.mark.new'), new_receipt_path({ :type => "MarkReceipt", :branch => "M" })) %></li>
    <li><%= link_to(I18n.t('menu.receipt.mark.rectification'), new_receipt_path({ :type => "RectificationMarkReceipt", :branch => "M" })) %></li>
    <li role="separator" class="divider"></li>
    <li><%= link_to(I18n.t('menu.receipt.search.identical'), new_receipt_path({ :type => "IdenticalSearchReceipt", :branch => "M" })) %></li>
    <li><%= link_to(I18n.t('menu.receipt.search.similitude'), new_receipt_path({ :type => "SimilarSearchReceipt", :branch => "M" })) %></li>
    <li role="separator" class="divider"></li>
    <li><%= link_to(I18n.t('menu.receipt.design.new'), new_receipt_path({ :type => "DesignReceipt", :branch => "M" })) %></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= I18n.t('activerecord.models.receipt.other') %><span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to I18n.t('menu.receipt.all'), receipts_path({ :type => "Receipt" }) %></li>
  </ul>
</li>