config/routes.rb
Rails.application.routes.draw do
  get 'settings/change_locale'

  # gems generated routes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # custom routes
  root to: "home#index"
  get 'home/info'
  get 'home/help'
  post '/orders/load' , to: 'orders#load'
  post '/receipts/tax_evaluation' , to: 'receipts#tax_evaluation'

  # resources routes
  # for receipts
  resources :receipts
  # resources :mark_receipts, as: "receipts", :controller => "receipts", :type => "MarkReceipt", :branch => "M",
  # resources :identical_search_receipts, :controller => "receipts", :type => "IdenticalSearchReceipt", :branch => "M", :path => 'receipts'
  # resources :similar_search_receipts, :controller => "receipts", :type => "SimilarSearchReceipt", :branch => "M", :path => 'receipts'
  # resources :rectification_mark_receipts, :controller => "receipts", :type => "RectificationMarkReceipt", :branch => "M", :path => 'receipts'
  # for orders
  resources :orders, :controller => "orders", only: [:new, :create, :show, :index]
  resources :md_orders, :controller => "orders", only: [:new, :show, :index]
  resources :pd_orders, :controller => "orders", only: [:new, :show, :index]
  resources :md_orders, :controller => "orders", only: [:create,], :formats=>[:json]
  resources :pd_orders, :controller => "orders", only: [:create], :formats=>[:json]

  # Cahnge locale routes
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/models/orders/md_order.rb
class MdOrder < Order
  # has_many :orderables, class_name: "MdOrderable", inverse_of: 'order', :foreign_key => "order_id"
  # has_many :receipts, through: :orderables, class_name: "MdReceipt", inverse_of: 'orders'
end

app/models/orders/md_orderable.rb
class MdOrderable < Orderable
  # belongs_to :order, class_name: "MdOrder", :foreign_key => "order_id"
  # belongs_to :receipt, class_name: "MdReceipt", :foreign_key => "receipt_id"
end

app/models/orders/order.rb
class Order < ApplicationRecord
  self.per_page = 10
  # include ImageUploader::Attachment.new(:image)
  has_many :orderables, inverse_of: 'order'
  has_many :receipts, through: :orderables, inverse_of: 'orders'
  belongs_to :user
  belongs_to :group
  has_one :payement
  has_one :transfer_payement
  has_one :check_payement
  accepts_nested_attributes_for :payement, :allow_destroy => true
  attr_accessor :name

  validates :payement, presence: true
  validates :group, :user, presence: true
  validates_associated :payement

  before_validation :initiate, on: :create

  filterrific(
    default_filter_params: { sorted_by: 'created_at_asc' },
    available_filters: [
      :sorted_by,
      :by_month,
      :by_year,
      :with_group_id,
      :with_type,
      :with_payement_type
    ]
  )

  scope :selectized, ->(query, number) { where('(payements.name ILIKE ? OR number= ?) AND remain > 0', "%#{query}%", number) }
  scope :with_group_id, ->(id) {where(group_id: id)}
  scope :with_type, ->(type) {where(type: type)}
  scope :with_payement_type, ->(payement_type) { where('payements.type = ?', payement_type ) }
  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("orders.created_at #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  def self.options_for_sorted_by
    [
      [I18n.t('tables.headers.timestamped')+ ' (asc)', 'created_at_asc'],
      [I18n.t('tables.headers.timestamped') + ' (desc)', 'created_at_desc']
    ]
  end

  def self.options_for_with_type
    [
      ['OP Marque', 'MdOrder'],
      ['OP Brevet', 'PdOrder']
    ]
  end

  def self.options_for_with_payement_type
    [
      ['Chèque', 'CheckPayement'],
      ['Versement', 'TransferPayement']
    ]
  end

  def self.options_for_by_month
    [
      ['Janvier', '1'],
      ['Fevrier', '2'],
      ['Mars', '3'],
      ['Avril', '4'],
      ['Mai', '5'],
      ['Juin', '6'],
      ['Juillet', '7'],
      ['Aout', '8'],
      ['Septembre', '9'],
      ['Octobre', '10'],
      ['Novembre', '11'],
      ['Decembre', '12']
    ]
  end

  def name
    return self.payement.name
  end

  private

  def initiate()
    self.number = set_number()
    self.remain = self.payement.value
  end

  def set_number
    number = Order.count()
    if number == 0 then
      return 1
    else
    number = Order.maximum(:number) + 1
    end
    return number
  end

end
require_dependency 'md_order'
require_dependency 'pd_order'

app/models/orders/orderable.rb
class Orderable < ApplicationRecord
    belongs_to :order
    belongs_to :receipt
end
require_dependency 'md_orderable'
require_dependency 'pd_orderable'

app/models/orders/payement_order.rb
class PayementOrder < ApplicationRecord
  # include ImageUploader::Attachment.new(:image)
  has_one :payement
  has_one :transfer_payement
  has_one :check_payement
  accepts_nested_attributes_for :payement, :allow_destroy => true
  # accepts_nested_attributes_for :transfer_payement, :allow_destroy => true
  # accepts_nested_attributes_for :check_payement, :allow_destroy => true


  before_validation :initiate, on: :create

  private

  def initiate()
    self.number = set_number()
  end

  def set_number
    number = PayementOrder.count() + 1
    return number
  end

end
require_dependency 'md_order'
require_dependency 'pd_order'

app/models/orders/pd_order.rb
class PdOrder < Order
  # has_many :orderables, class_name: "PdOrderable", inverse_of: 'order', :foreign_key => "order_id"
  # has_many :receipts, through: :orderables, class_name: "PdReceipt", inverse_of: 'orders'
end

app/models/orders/pd_orderable.rb
class PdOrderable < Orderable
  # belongs_to :order, class_name: "PdOrder", :foreign_key => "order_id"
  # belongs_to :receipt, class_name: "PdReceipt", :foreign_key => "receipt_id"
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session
  load_and_authorize_resource

  def load
    query = params[:query]
    number = query.to_i
    @orders = Order.joins(:payement).selectized(query, number)
    respond_to do |format|
        format.json {render json: @orders.to_json(:methods => [:id, :number, :name, :remain])}
    end
  end

  def index
    @filterrific = initialize_filterrific(
      Order.joins(:payement).includes(:payement),
      params[:filterrific],
      select_options: {
        with_group_id: Group.options_for_select,
        with_type: Order.options_for_with_type,
        with_payement_type: Order.options_for_with_payement_type,
        by_month: Order.options_for_by_month,
        sorted_by: Order.options_for_sorted_by
      },
      default_filter_params: { sorted_by: 'created_at_asc' },
    ) or return

    respond_to do |format|
      format.html {
        @orders = @filterrific.find.page(params[:page])
      }
      format.js {
        @orders = @filterrific.find.page(params[:page])
      }
      format.xlsx {
        @orders = @filterrific.find
        render xlsx: "orders", 
        template: 'orders/index', 
        disposition: 'inline', 
        locals: {xlsx_author: current_user.fullname}
      }
    end

    rescue ActiveRecord::RecordNotFound => e
      puts "Had to reset filter params: #{ e.message }"
      redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def new
    @order = order_type.new
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.group_id = current_user.group.id
    respond_to do |format|
      if @order.save
        format.json { render json: @order.to_json(:methods => [:id, :number, :name, :remain]) }
      else
        format.json { render json: @order.errors }
      end
    end
  end

  def show
    render json:@order
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:image, :type, payement_attributes:[:type,
      :value, :name, :date, :image, :serie, :number, :ref, :state, :_destroy])
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
  def new_order
    @order = Order.new
  end

  def order_types
    ["M", "P"]
  end

  def order_type
    if params[:branch].in? order_types
      if params[:branch] = "M"
        return "MdOrder"
      elsif params[:branch] = "P"
        return "PdOrder"
      end
    end
  end
end

app/views/orders/_list.html.erb
<div class="well well-sm">
  <div class="chardin_box" data-intro="will_paginate's entries info works as expected." data-position="bottom">
    <%= page_entries_info orders %>
  </div>
  <div class="chardin_box" data-intro="Spinner indicates update." data-position="bottom">
    <%= render_filterrific_spinner %>
  </div>
</div>

<table class="table table-bordered">
<thead class="thead-light">
  <tr class="active">
    <th class="centered"><%= I18n.t('tables.headers.number') %></th>
    <th class="centered"><%= I18n.t('tables.headers.by') %></th>
    <th class="centered"><%= I18n.t('tables.headers.timestamped') %></th>
    <th class="centered"><%= I18n.t('tables.headers.value') %></th>
  </tr>
</thead>
<tbody>
  <% orders.each do |order| %>
    <tr class="order">
      <td class="number centered">
        <%= order.number %>
      </td>
      <td class="name centered">
        <%= order.payement.name %>
      </td>
      <td class="created_at centered">
        <%= I18n.l order.created_at %>
      </td>
      <td class="value">
        <%= number_to_currency(order.payement.value) %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>

<div class="chardin_box" data-intro="will_paginate's paginator works as expected." data-position="top">
  <%= will_paginate orders, renderer: BootstrapPagination::Rails %>
</div>

app/views/orders/_order_fields.html.erb
<%= simple_form_for(@order=new_order, wrapper: :inline_form) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :type, :value => order_type %>
  <%= f.input :image, as: :file %>
  <div id="payement">
    <%= f.simple_fields_for :payement do |payement| %>
    <%= render 'payement_fields', :f => payement %>
    <% end %>
  </div>
  <div class="row links">
    <div class="col col-md-8">
    <%= link_to_add_association('versement', f, :payement, data: {association_insertion_node: '#payement', association_insertion_method: :append}, :class => "btn btn-success btn-xs",
    wrap_object: Proc.new { |payement| payement.type = "TransferPayement"; payement = TransferPayement.new }) %>
    <%= link_to_add_association('chèque', f, :payement, data: {association_insertion_node: '#payement', association_insertion_method: :append}, :class => "btn btn-success btn-xs",
    wrap_object: Proc.new { |payement| payement.type = "CheckPayement"; payement = CheckPayement.new }) %>
    </div>
    <div class="col col-md-4">
      <%= f.submit class: "btn btn-info pull-right", id: "new_order_submit" %>
    </div>
  </div>

<% end %>

app/views/orders/_order_modal.html.erb
<div class="modal fade order-modal" id="myModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">new payement order</h4>
      </div>
      <div class="modal-body">
        <%= render :partial => "orders/order_fields"%>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="row">
<div class="col col-md-9" id="results">
  <%= render(:partial => 'orders/list', :locals => { :orders => @orders }) %>
</div>

<div class="col-md-3">
<div class="panel panel-default">
  <div class="panel-heading">
  <h4><%= I18n.t('menu.filter.head') %></h4>
  </div>
  <div class="panel-body">
  <%= form_for_filterrific @filterrific do |f| %>
    <div class="form-group chardin_box" data-intro="Filter by month." data-position="left">
      <label><%= I18n.t('datetime.prompts.month')%></label>
      <%= f.select(:by_month, @filterrific.select_options[:by_month], { :include_blank => '- ' + I18n.t('menu.filter.all') + ' -' }, { :class => 'form-control' }) %>
      <div class="form-group chardin_box" data-intro="Filter by year." data-position="left">
        <label><%= I18n.t('datetime.prompts.year')%> </label>
        <%= f.text_field :by_year, :class => 'filterrific-periodically-observed form-control' %>
      </div>
      <div class="form-group chardin_box" data-intro="Filter by group." data-position="left">
        <label><%= I18n.t('activerecord.models.group.one') %></label>
        <%= f.select(:with_group_id, @filterrific.select_options[:with_group_id], { :include_blank => '- ' + I18n.t('menu.filter.all') + ' -' }, { :class => 'form-control' }) %>
      </div>
      <div class="form-group chardin_box" data-intro="Filter by type." data-position="left">
        <label><%= I18n.t('menu.filter.type') %></label>
        <%= f.select(:with_type, @filterrific.select_options[:with_type], { :include_blank => '- ' + I18n.t('menu.filter.all') + ' -' }, { :class => 'form-control' }) %>
      </div>
      <div class="form-group chardin_box" data-intro="Filter by payement type." data-position="left">
        <label><%= I18n.t('menu.filter.payement.type') %></label>
        <%= f.select(:with_payement_type, @filterrific.select_options[:with_payement_type], { :include_blank => '- ' + I18n.t('menu.filter.all') + ' -' }, { :class => 'form-control' }) %>
      </div>
      <div class="form-group chardin_box" data-intro="Change the sorting." data-position="left">
        <label><%= I18n.t('menu.filter.order') %></label>
        <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], {}, { :class => 'form-control' }) %>
      </div>
    </div>
    <div class="chardin_box" data-intro="Export orders data to xlsx file." data-position="bottom">
      <%= link_to "Download(Excel)", orders_path(:format => :xlsx), :class => 'btn btn-primary btn-sm', target: :_blank  %>
      <%= link_to "Reset", orders_url + "?filterrific%5Breset_filterrific%5D=true", :class => 'btn btn-default btn-sm pull-right' %>
    </div>
  <% end %>
  </div>
  </div>
</div>
</div>

app/views/orders/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'orders/list',
    :locals => { :orders => @orders }
  )
) %>
$("#results").html("<%= js %>");