config/routes.rb
Rails.application.routes.draw do
  get 'settings/change_locale'

  # gems generated routes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # custom routes
  root to: "home#index"
  get 'home/info'
  get 'home/help'
  post '/orders/load' , to: 'orders#load'
  post '/receipts/tax_evaluation' , to: 'receipts#tax_evaluation'

  # resources routes
  # for receipts
  resources :receipts
  # resources :mark_receipts, as: "receipts", :controller => "receipts", :type => "MarkReceipt", :branch => "M",
  # resources :identical_search_receipts, :controller => "receipts", :type => "IdenticalSearchReceipt", :branch => "M", :path => 'receipts'
  # resources :similar_search_receipts, :controller => "receipts", :type => "SimilarSearchReceipt", :branch => "M", :path => 'receipts'
  # resources :rectification_mark_receipts, :controller => "receipts", :type => "RectificationMarkReceipt", :branch => "M", :path => 'receipts'
  # for orders
  resources :orders, :controller => "orders", only: [:new, :create, :show, :index]
  resources :md_orders, :controller => "orders", only: [:new, :show, :index]
  resources :pd_orders, :controller => "orders", only: [:new, :show, :index]
  resources :md_orders, :controller => "orders", only: [:create,], :formats=>[:json]
  resources :pd_orders, :controller => "orders", only: [:create], :formats=>[:json]

  # Cahnge locale routes
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/models/receipts/design_receipt.rb
class DesignReceipt < MdReceipt
  jsonb_accessor :data,
    models: [:integer, default: 1],
    draws: [:integer, default: 0],
    pics: [:integer, default: 1],
    base_tax: :decimal,
    models_tax: :decimal,
    holding_tax: :decimal,
    draws_tax: :decimal,
    pics_tax: :decimal

  validates :models, :numericality => { :greater_than_or_equal_to => 1 }
  validates :draws, :pics, :numericality => { :greater_than_or_equal_to => 0 }
  validates_numericality_of :models, less_than_or_equal_to: ->(design_receipt) { design_receipt.draws + design_receipt.pics }

  def tax_calculate
    tax_line = Tax.where(code: "747-00", category: "base").first
    self.base_tax = tax_line.current_tax
    tax_line = Tax.where(code: "747-01", category: "model").first
    self.models_tax = tax_line.current_tax
    tax_line = Tax.where(code: "747-04", category: "holding").first
    self.holding_tax = tax_line.current_tax
    tax_line = Tax.where(code: "747-03", category: "draws").first
    self.draws_tax = tax_line.current_tax
    tax_line = Tax.where(code: "747-03", category: "pictures").first
    self.pics_tax = tax_line.current_tax
    self.total = self.base_tax + ((self.models_tax + self.holding_tax) * self.models) + (self.draws_tax * self.draws) + (self.pics_tax * self.pics)
  end
end

app/models/receipts/identical_search_receipt.rb
class IdenticalSearchReceipt < MdReceipt
  jsonb_accessor :data,
    number_searches: [:integer, default: 1],
    number_additional_classes: [:integer, default: 0],
    base_tax: :decimal,
    class_tax: :decimal

  validates :number_searches, :number_additional_classes, presence: true
  validates :number_searches, :numericality => { :greater_than_or_equal_to => 1 }
  validates :number_additional_classes, :numericality => { :greater_than_or_equal_to => 0 }
  validates_numericality_of :number_additional_classes,  less_than_or_equal_to: ->(identical_search_receipt) { identical_search_receipt.number_searches * 44 }

  def tax_calculate
    tax_line = Tax.where(code: "746-07", category: "base").first
    self.base_tax = tax_line.current_tax
    tax_line = Tax.where(code: "746-07", category: "class").first
    self.class_tax = tax_line.current_tax
    self.total = (self.number_searches * self.base_tax) + 
      (self.number_additional_classes * self.class_tax)
  end
end

app/models/receipts/mark_receipt.rb
class MarkReceipt < MdReceipt
  jsonb_accessor :data,
    mark_name: :string,
    mark_type: [:integer, default: 2],
    colored: [:boolean, default: true],
    classes: [:integer, default: 1],
    rev_pri: [:boolean, default: false],
    international: [:boolean, default: false],
    ipas_num: :integer,
    base_tax: :decimal,
    class_tax: :decimal,
    rev_tax: :decimal,
    int_tax: :decimal

  enum mark_type: [:figuratif, :verbal, :figuratif_and_verbal]


  validates :mark_name, presence: true, unless: :pictured?
  validates :mark_name, absence: true, if: :pictured?
  validates :colored, exclusion: { in: [true] }, if: :verbalized?
  validates :classes, inclusion: { in: 1..45 }

  def verbalized?
    mark_type == 'verbal'
  end

  def pictured?
    mark_type == 'figuratif'
  end

  def tax_calculate
    if self.colored? then
      tax_line = Tax.where(code: "746-01", category: "colored").first
    else
      tax_line = Tax.where(code: "746-01", category: "uncolored").first
    end
    self.base_tax = tax_line.current_tax
    tax_line = Tax.where(code: "746-02").first
    self.class_tax = tax_line.current_tax
    if self.rev_pri? then
      tax_line = Tax.where(code: "746-03").first
      self.rev_tax = tax_line.current_tax
    else
      self.rev_tax = 0
    end
    if self.international? then
      tax_line = Tax.where(code: "746-15").first
      self.int_tax = tax_line.current_tax
    else
      self.int_tax = 0
    end
    self.total = self.base_tax + (self.class_tax * self.classes) + self.rev_tax + self.int_tax
  end
end

app/models/receipts/md_receipt.rb
class MdReceipt < Receipt
  # has_many :orderables, class_name: "MdOrderable", inverse_of: 'receipt', dependent: :destroy
  # has_many :orders, through: :orderables, class_name: "MdOrder", inverse_of: 'receipts'

  def set_number
    number = MdReceipt.where(serie: Date.current.year).count()
    if number == 0 then
      return 1
    else
      number = MdReceipt.where(serie: Date.current.year).maximum(:number) + 1
      return number
    end
  end
  
  def branching
    return 0
  end
end
require_dependency 'mark_receipt'
require_dependency 'similar_search_receipt'
require_dependency 'identical_search_receipt'
require_dependency 'rectification_mark_receipt'
require_dependency 'design_receipt'

app/models/receipts/pd_receipt.rb
class PdReceipt < Receipt
  # has_many :orderables, class_name: "PdOrderable", inverse_of: 'receipt', :foreign_key => "receipt_id", dependent: :destroy
  # has_many :orders, through: :orderables, class_name: "PdOrder", inverse_of: 'receipts'

  def set_number
    number = PdReceipt.where(serie: Date.current.year).count()
    if number == 0 then
      return 1
    else
      number = PdReceipt.where(serie: Date.current.year).maximum(:number) + 1
      return number
    end
  end

  def branching
    return 1
  end
end

app/models/receipts/receipt.rb
class Receipt < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  belongs_to :representative, optional: true
  belongs_to :user
  belongs_to :group
  has_many :orderables, inverse_of: 'receipt', dependent: :destroy
  has_many :orders, through: :orderables, inverse_of: 'receipts'
  has_many :payements, through: :orders

  validates :order_ids, presence: true
  validates :group, :user, presence: true
  validate :sum_remain_must_be_enough, on: :create
  validate :sum_used_must_be_enough, on: :update

  before_validation :valuate, on: :create

  jsonb_accessor :owner_adress,
    owner_street: :string,
    owner_wilaya: :string

  validates :owner_name, :owner_street, :owner_wilaya, :type, :branch, presence: true
  validates :number, uniqueness: { :scope => [:serie, :branch] }

  enum status: { active: 0, inactive: 1 }
  enum branch: { M: 0, P: 1 }

  enum owner_wilaya: { "Adrar" => "Adrar",
    "Chlef"           => "Chlef",
    "Laghouat"   => "Laghouat",
    "Oum El Bouaghi"     => "Oum El Bouaghi",
    "Batna" => "Batna",
    "Béjaïa" => "Béjaïa",
    "Biskra" => "Biskra",
    "Béchar" => "Béchar",
    "Blida" => "Blida",
    "Bouira" => "Bouira",
    "Tamanrasset" => "Tamanrasset",
    "Tébessa" => "Tébessa",
    "Tlemcen" => "Tlemcen",
    "Tiaret" => "Tiaret",
    "Tizi Ouzou" => "Tizi Ouzou",
    "Alger" => "Alger",
    "Djelfa" => "Djelfa",
    "Jijel" => "Jijel",
    "Sétif" => "Sétif",
    "Saïda" => "Saïda",
    "Skikda" => "Skikda",
    "Sidi Bel Abbès" => "Sidi Bel Abbès",
    "Annaba" => "Annaba",
    "Guelma" => "Guelma",
    "Constantine" => "Constantine",
    "Médéa" => "Médéa",
    "Mostaganem" => "Mostaganem",
    "M'Sila" => "M'Sila",
    "Mascara" => "Mascara",
    "Ouargla" => "Ouargla",
    "Oran" => "Oran",
    "El Bayadh" => "El Bayadh",
    "Illizi" => "Illizi",
    "Bordj Bou Arreridj" => "Bordj Bou Arreridj",
    "Boumerdès" => "Boumerdès",
    "El Tarf" => "El Tarf",
    "Tindouf" => "Tindouf",
    "Tissemsilt" => "Tissemsilt",
    "El Oued" => "El Oued",
    "Khenchela" => "Khenchela",
    "Souk Ahras" => "Souk Ahras",
    "Tipaza" => "Tipaza",
    "Mila" => "Mila",
    "Aïn Defla" => "Aïn Defla",
    "Naâma" => "Naâma",
    "Aïn Témouchent" => "Aïn Témouchent",
    "Ghardaïa" => "Ghardaïa",
    "Relizane" => "Relizane"
    }

  def setting_op
    transaction do
      save
      value_comp = total
      id = self.id
      orders.each do |order|
        if value_comp.positive? && order.remain.positive?
          if order.remain >= value_comp
            @orderable = order.orderables.where(receipt_id: id, order_id: order.id).update(
              used: value_comp
              )
            order.remain = order.remain - value_comp
            value_comp = 0
            order.save
          elsif order.remain < value_comp
            value_comp -= order.remain
            @orderable = order.orderables.where(receipt_id: id, order_id: order.id).update(
              used: order.remain
              )
            order.remain = 0
            order.save
          end
        end
      end
    end
  end

  def making_credit
    transaction do
      self.inactive
      save
      id = self.id
      orders.each do |order|
        @orderable = order.orderables.where(receipt_id: id, order_id: order.id)
        order.remain += @orderable.used
        order.save
        @orderable.destroy
      end
    end
  end

  def paid_sum
    total = 0
    orders.each do |order|
      total += order.remain
    end
    total
  end

  def used_sum
    total = 0
    orderables.each do |orderable|
      total += orderable.used
    end
    total
  end

  private

  def sum_remain_must_be_enough
    errors.add(:order_ids, :not_enough) if total > paid_sum
  end

  def sum_used_must_be_enough
    errors.add(:order_ids, :not_enough_used) if total > used_sum
  end

  def valuate
    self.serie = Date.current.year
    self.number = set_number
    self.branch = branching
    Tax.updating
    tax_calculate
  end

end
require_dependency 'md_receipt'
require_dependency 'pd_receipt'

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  rescue_from ActiveRecord::RecordInvalid, with: :show_errors
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /receipts
  # GET /receipts.json
  def index
    if receipt_type
      @receipts = receipt_type.includes(:representative).all
    else
      redirect_to root_url
    end
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
    if receipt_type
      # @receipt = receipt_type.find(params[:id])
      respond_to do |format|
        format.html
        format.pdf do
          @payements = @receipt.payements
          pdf = ReceiptPdf.new(@receipt, @payements)
          send_data pdf.render,
            filename: "receipt_#{@receipt.serie}_#{@receipt.number}",
            type: 'application/pdf',
            disposition: 'inline'
        end
      end
    else
      redirect_to root_url
    end
  end

  # GET /receipts/new
  def new
    Tax.updating
    @receipt = receipt_type.new
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts
  # POST /receipts.json
  def create
      @receipt = receipt_type.new(receipt_params)
      @receipt.user_id = current_user.id
      @receipt.group_id = current_user.group.id
      respond_to do |format|
        if @receipt.valid?
          @receipt.setting_op
          format.html { redirect_to receipt_url({ :type => @receipt.type, :id => @receipt.id }), notice: I18n.t('notices.receipt.created') }
          format.js { redirect_to receipt_url({ :type => @receipt.type, :id => @receipt.id }), notice: I18n.t('notices.receipt.created') }
          format.json { render :show, status: :created, location: @receipt }
        else
          format.html { render :new }
          format.json { render json: @receipt.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /receipts/1
  # PATCH/PUT /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_update_params)
        format.html { redirect_to receipt_url({ :type => @receipt.type, :id => @receipt.id }), notice: 'Receipt was successfully updated.' }
        format.js { redirect_to receipt_url({ :type => @receipt.type, :id => @receipt.id }), notice: 'Receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt.making_credit
    respond_to do |format|
      format.html { redirect_to customized_url, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tax_evaluation
    @receipt = receipt_type.new(receipt_update_params)
      @receipt.tax_calculate
      respond_to do |format|
        format.json { render 'receipts/tax_evaluation' }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = receipt_type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      if params[:type] == "MarkReceipt" then
        params.require(:mark_receipt).permit(:owner_name, :type, :owner_adress, :representative_id, :owner_street, :owner_wilaya, :mark_name, :image,
        :mark_type, :colored, :classes, :rev_pri, :ipas_num, :order_ids => [])
      elsif params[:type] == "IdenticalSearchReceipt" then
        params.require(:identical_search_receipt).permit(:owner_name, :type, :owner_adress, :representative_id, :owner_street, :owner_wilaya, :image,
        :number_searches, :number_additional_classes, :order_ids => [])
      elsif params[:type] == "SimilarSearchReceipt" then
        params.require(:similar_search_receipt).permit(:owner_name, :type, :owner_adress, :representative_id, :owner_street, :owner_wilaya, :image,
        :number_searches, :number_searches_with_more_than_three_classes, :order_ids => [])
      elsif params[:type] == "RectificationMarkReceipt" then
        params.require(:rectification_mark_receipt).permit(:owner_name, :type, :owner_adress, :representative_id, :owner_street, :owner_wilaya, :image,
        :number_marks, :order_ids => [])
      elsif params[:type] == "DesignReceipt" then
        params.require(:design_receipt).permit(:owner_name, :type, :owner_adress, :representative_id, :owner_street, :owner_wilaya, :image,
        :models, :draws, :pics, :order_ids => [])
      end
    end

    def receipt_update_params
      if params[:type] == "MarkReceipt" then
        params.require(:mark_receipt).permit(:owner_name, :type, :owner_adress, :representative_id, :owner_street, :owner_wilaya, :mark_name, :image,
        :mark_type, :colored, :classes, :rev_pri, :ipas_num)
      elsif params[:type] == "IdenticalSearchReceipt" then
        params.require(:identical_search_receipt).permit(:owner_name, :type, :owner_adress, :representative_id, :owner_street, :owner_wilaya, :image,
        :number_searches, :number_additional_classes)
      elsif params[:type] == "SimilarSearchReceipt" then
        params.require(:similar_search_receipt).permit(:owner_name, :type, :owner_adress, :representative_id, :owner_street, :owner_wilaya, :image,
        :number_searches, :number_searches_with_more_than_three_classes)
      elsif params[:type] == "RectificationMarkReceipt" then
        params.require(:rectification_mark_receipt).permit(:owner_name, :type, :owner_adress, :representative_id, :owner_street, :owner_wilaya, :image,
        :number_marks)
      elsif params[:type] == "DesignReceipt" then
        params.require(:design_receipt).permit(:owner_name, :type, :owner_adress, :representative_id, :owner_street, :owner_wilaya, :image,
        :models, :draws, :pics)
      end
    end

    def customized_url
      "/" + params[:type].tableize if params[:type].in? receipt_types
    end

    def receipt_type
      params[:type].constantize if params[:type].in? receipt_types
    end

    def receipt_types
      ["Receipt", "MarkReceipt", "IdenticalSearchReceipt", "SimilarSearchReceipt", "RectificationMarkReceipt", "DesignReceipt"]
    end

end

app/helpers/receipts_helper.rb
module ReceiptsHelper

  def customized_url
    "/" + params[:type].tableize if params[:type].in? receipt_types
  end

  private
  def receipt_types
    ["MarkReceipt", "IdenticalSearchReceipt", "SimilarSearchReceipt", "RectificationMarkReceipt",  "DesignReceipt"]
  end

  def receipt_form_url
    if @receipt.new_record? 
      return (receipts_path({ :type => @receipt.type }))
    else
      return (receipt_path({ :type => @receipt.type, :id => @receipt.id }))
    end
  end
end

app/views/receipts/_form.html.erb
<%= simple_form_for(@receipt, url: receipt_form_url,
 remote: true, validate: true, wrapper: :inline_form, :html => {:id => "receipt"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col col-md-6"> <%= f.input :owner_name %> </div>
      <div class="col col-md-6"> <%= f.association :representative, label_method: :fullname, input_html: { class: "representative" },
      prompt: t('simple_form.prompts.receipt.representative'), wrapper: :selectize_mutlti %> </div>
    </div>
    <div class="row">
      <div class="col col-md-8"> <%= f.input :owner_street %> </div>
      <div class="col col-md-4"> <%= f.input :owner_wilaya, as: :select, wrapper: :selectize_mutlti,
      collection: Receipt.owner_wilayas, selected: current_user.group.name, input_html: { class: "wilaya" } %> </div>
    </div>
    <%= render :partial => "form_cases", :locals=>{:f=>f} %>
    <%= f.input :image, as: :hidden, input_html: {value: @receipt.cached_image_data} %>
    <%= f.input :image, as: :file %>
    <hr />
    <% if receipt_new == "new" then %>
      <%= f.association :orders, as: :select, collection: {}, :multiple => true, 
      wrapper: :selectize_mutlti, :placeholder => true, input_html: {:id => "receipt_orders"} %>
    <% end %>
    <hr />
    <div class="row">
    <div class="col col-md-6" id="total-tax">
      <% if receipt_new == "new" then %>
      Total: <div id="total-value"><%= number_to_currency(@receipt.tax_calculate) %></div>
      <% end %>
    </div>
  <div class="col col-md-6">
    <div class="form-actions">
      <%= f.button :submit, :class => 'pull-right' %>
    </div>
    <% end %>
  </div>
  </div>

app/views/receipts/_form_cases.html.erb
<% if params[:type]=="MarkReceipt" %>
  <div class='row'>
    <%= f.input :type, as: :hidden, input_html: {id:"receipt_type", value: "MarkReceipt"} %>
    <div class="col col-md-6"> <%= f.input :mark_name %> </div>
    <div class="col col-md-6"> <%= f.input :mark_type, include_blank: false %> </div>
  </div>
  <div class="row receipt_tax_value_inputs">
    <div class="col col-md-3"> <%= f.input :classes, hint: true %> </div>
    <div class="col col-md-3"> <%= f.input :ipas_num %> </div>
    <div class="col col-md-3"> <%= f.input :colored %> </div>
    <div class="col col-md-3"> <%= f.input :rev_pri %> </div>
  </div>
<% elsif params[:type]=="IdenticalSearchReceipt" %>
<%= f.input :type, as: :hidden, input_html: {id:"receipt_type", value: "IdenticalSearchReceipt"} %>
  <div class="row receipt_tax_value_inputs">
    <div class="col col-md-6"> <%= f.input :number_searches %> </div>
    <div class="col col-md-6"> <%= f.input :number_additional_classes %> </div>
  </div>
<% elsif params[:type]=="SimilarSearchReceipt" %>
  <div class="row receipt_tax_value_inputs">
  <%= f.input :type, as: :hidden, input_html: {id:"receipt_type", value: "SimilarSearchReceipt"} %>
    <div class="col col-md-6"> <%= f.input :number_searches %> </div>
    <div class="col col-md-6"> <%= f.input :number_searches_with_more_than_three_classes %>
    </div>
  </div>
<% elsif params[:type]=="RectificationMarkReceipt" %>
  <div class="row receipt_tax_value_inputs">
  <%= f.input :type, as: :hidden, input_html: {id:"receipt_type", value: "RectificationMarkReceipt"} %>
    <div class="col col-md-12"> <%= f.input :number_marks %> </div>
  </div>
<% elsif params[:type]=="DesignReceipt" %>
<div class="row receipt_tax_value_inputs">
<%= f.input :type, as: :hidden, input_html: {id:"receipt_type", value: "DesignReceipt"} %>
<div class="col col-md-4"><%= f.input :models, hint: true %></div>
<div class="col col-md-4"><%= f.input :draws, hint: true %></div>
<div class="col col-md-4"><%= f.input :pics, hint: true %></div>
</div>
<% end %>

app/views/receipts/_nested_buttons.html.erb
<% if defined? f %>

<% end %>

app/views/receipts/_payement_fields.html.erb
<div class="panel panel-info nested-fields">
  <div class="panel-heading">New Payement
    <%= link_to_remove_association '', f, class: "close glyphicon glyphicon-remove close-link" %>
  </div>
  <div class="panel-body">

<% if f.object.type == "TransferPayement" %>
  <div>
    <%= f.hidden_field :type, :value => "TransferPayement" %>
    <%= f.input :date, as: :string, input_html: { class: "datepicker", autocomplete: 'off'}  %>
    <%= f.input :value, hint: true, input_html: {value: ""} %>
    <%= f.input :name %>
    <%= f.input :ref, placeholder: true %>
    <%= f.input :image, as: :file %>
  </div>
<% elsif f.object.type  == "CheckPayement" %>
  <div>
    <%= f.hidden_field :type, :value => "CheckPayement" %>
    <%= f.input :date, as: :string, input_html: { class: "datepicker", autocomplete: 'off'}  %>
    <%= f.input :value, hint: true, input_html: {value: ""} %>
    <%= f.input :name %>
    <%= f.input :number, placeholder: true %>
    <%= f.input :image, as: :file %>
  </div>
<% end %>
</div>
</div>

app/views/receipts/_payement_fields.thml.erb
<% if defined? payement_type %>
<% if payement_type == "transfer" %>
  <div>
    <%= f.simple_fields_for f.object.transfer_payement do |p| %>
    <%= p.input :type, :as => :hidden, :input_html => { :value => "TransferPayement" } %>
    <%= p.input :date %>
    <%= p.input :value %>
    <%= p.input :name %>
    <%= p.input :ref %>
    <%= p.input :image, as: :file %>
    <% end %>
  </div>
<% elsif payement_type == "check" %>
  <div>
    <%= f.simple_fields_for :payement do |p| %>
    <%= p.input :type, :as => :hidden, :input_html => { :value => "CheckPayement" } %>
    <%= p.input :date %>
    <%= p.input :value %>
    <%= p.input :name %>
    <%= p.input :number %>
    <%= p.input :image, as: :file %>
    <% end %>
  </div>
<% end %>
<% end %>

app/views/receipts/_show_cases.html.erb
<% if params[:type] == "MarkReceipt" then %>
    <strong><%= I18n.t('menu.receipt.attributes.classes') %>:</strong> <%= @receipt.classes %><br />
<% elsif params[:type] == "IdenticalSearchReceipt" then %>
    <strong><%= I18n.t('menu.receipt.attributes.number_searches') %>: </strong> <%= @receipt.number_searches %><br />
    <strong><%= I18n.t('menu.receipt.attributes.classes_plus') %>: </strong> <%= @receipt.number_additional_classes %><br />
<% elsif params[:type] == "SimilarSearchReceipt" then %>
    <strong><%= I18n.t('menu.receipt.attributes.number_searches') %>: </strong> <%= @receipt.number_searches %><br />
    <strong><%= I18n.t('menu.receipt.attributes.classes_plus_three') %>: </strong> <%= @receipt.number_searches_with_more_than_three_classes %><br />
<% elsif params[:type] == "RectificationMarkReceipt" then %>
    <strong><%= I18n.t('menu.receipt.attributes.number_marks') %>: </strong> <%= @receipt.number_marks %><br />
<% elsif params[:type] == "DesignReceipt" then %>
    <strong><%= I18n.t('menu.receipt.attributes.models') %>: </strong> <%= @receipt.models %><br />
    <strong><%= I18n.t('menu.receipt.attributes.draws') %>: </strong> <%= @receipt.draws %><br />
    <strong><%= I18n.t('menu.receipt.attributes.pics') %>: </strong> <%= @receipt.pics %><br />
<% end %>

app/views/receipts/edit.html.erb
<div class="panel panel-info">
  <div class="panel-heading"><%= I18n.t('menu.receipt.edit') %></div>
  <div class="panel-body">
  <%= render 'form', receipt: @receipt, receipt_new:"old" %>
  </div>
</div>

app/views/receipts/index.html.erb
<div class="panel panel-info">
<div class="panel-heading">
<h1 class="panel-title"><%= I18n.t('activerecord.models.receipt.other') %></h1></div>
<div class="panel-body">

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="col-md-1"><%= Receipt.human_attribute_name("number") %></th>
      <th class="col-md-2"><%= Receipt.human_attribute_name("owner_name") %></th>
      <th class="col-md-5"><%= Receipt.human_attribute_name("owner_street") %></th>
      <th class="col-md-2"><%= Representative.model_name.human %></th>
      <th colspan="3" class="text-center col-md-2"><%= I18n.t("menu.action.other") %></th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.number %>/<%= receipt.serie %></td>
        <td><%= receipt.owner_name %></td>
        <td><%= receipt.owner_street %>, <%= receipt.owner_wilaya %></td>
        <td><%= receipt.representative.fullname unless receipt.representative.nil?  %></td>
        <td><%= link_to t('menu.show'), receipt_path({:type => receipt.type, :id => receipt.id}), class: "btn btn-success btn-xs btn-block" %></td>
        <td><%= link_to t('menu.edit'), edit_receipt_path({:type => receipt.type, :id => receipt.id}), class: "btn btn-warning btn-xs btn-block" %></td>
        <td><%= link_to t('menu.disable'), receipts_path({:type => receipt.type, :id => receipt.id}), method: :delete, data: { confirm: t('menu.if_sure') }, class: "btn btn-danger btn-xs btn-block" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to t('menu.home'), "/", class: "btn btn-success" %>
<% if params[:type].in?(["Receipt"]) == false %>
<%= link_to t('menu.receipt.new'), customized_url + "/new", class: "btn btn-info pull-right" %>
<% end %>

</div>
</div>